-- This script was generated by the Supabase CLI.
--
-- Data:
--   Schema: public
--   Table: daycares
--
-- Ran on: 2026-08-12

begin;

-- Create the daycares table
create table public.daycares (
  id         uuid primary key default gen_random_uuid(),
  name       text        not null,
  address    text,
  created_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table public.daycares enable row level security;

-- Policy: Service role full access
create policy "Service role full access"
  on public.daycares
  for all
  to service_role
  using (true)
  with check (true);

commit;
